#Configuration for QuickcastAPI

#Define the Renderer
#Possible Values: NONE, CHAT, ACTION_BAR
renderer: 'ACTION_BAR'
#Define the text color of the renderer
color: '&6'

#Define the Timeout in seconds after the KeyCombination gets removed and player needs to restart the KeyCombination
timeout: 2

#Define the maximum Length of a Quickcast KeyCombination
max-length: 4